webapp/core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace='todo')),
    path("__reload__/", include("django_browser_reload.urls")),

]

webapp/core/todo/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from todo import views

app_name = 'todo'
urlpatterns = [
    path('todos/<str:chat_id>',csrf_exempt(views.Index),name='index'),
    path('todos/delete/<int:id>',views.remove_todo,name='delete'),
    path('todos/complete/<int:id>',views.complete_todo,name='complete'),
    path('todos/add/<str:chat_id>',csrf_exempt(views.add_todo),name='add'),
]

webapp/core/todo/models.py
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, BaseUserManager
from django.db import models
from django_jalali.db.models import jDateTimeField,jManager


class UserManager(BaseUserManager):
    def create_user(self, username=None, chat_id=None, password=None, **extra_fields):
        if not username and not chat_id:
            raise ValueError('Users must have username or chat_id')
        user = None
        if username and username == 'admin':
            user = self.model(username=username, **extra_fields)
            user.set_password(password)
            user.save(using=self._db)
        if chat_id:
            user = self.model(chat_id=chat_id, **extra_fields)
            user.set_unusable_password()
            user.save(using=self._db)
        return user

    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        return self.create_user(username=username, password=password, **extra_fields)
    # Create your models here.


class User(PermissionsMixin, AbstractBaseUser):
    chat_id = models.CharField(unique=True, blank=True, null=True)
    username = models.CharField(unique=True, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username if self.username else str(self.chat_id)


class Todo(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='todos')
    title = models.CharField(max_length=125)
    is_completed = models.BooleanField(default=False)
    created_at = jDateTimeField(auto_now_add=True)
    objects = jManager()

webapp/core/todo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from todo.models import User


class CreateUserForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput,required=False)
    password2 = forms.CharField(label='conf Password', widget=forms.PasswordInput,required=False)
    class Meta:
        model = User
        fields = ('username', 'chat_id')


class ChangeUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'chat_id', 'password')

webapp/core/todo/views.py
import json
import time
import math

from django.core.cache import cache
from django.core.serializers import serialize
from django.http import HttpResponse, StreamingHttpResponse, JsonResponse, Http404
from django.shortcuts import render
from django.template.loader import render_to_string

from todo.models import Todo, User


# Create your views here.
def Index(request,chat_id):
    if not chat_id:
        return Http404('bad request')
    if not User.objects.filter(chat_id=chat_id).exists():
        User.objects.create(chat_id = chat_id)
    if request.headers.get('Accept') == 'text/event-stream':
        response = loader(chat_id)
        return response

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        todos_list = cache.get(f'todos-{chat_id}')
        data = render_to_string('html/todos_list.html', context={'todos': todos_list})
        return HttpResponse(data)
    return render(request, 'html/index.html', {})

# def prepare_user(reqeust):
#     print(reqeust.POST)
#     return JsonResponse({})
def loader(chat_id):
    todos_filter = Todo.objects.filter(user__chat_id=chat_id).order_by('-created_at').values('id', 'title',
                                                                                             'is_completed')
    todo_count = todos_filter.count()
    chunking_limit = math.ceil(todo_count / 100 * 10)

    def chunking_data():
        todos_list = []
        start = 0
        end = chunking_limit
        for i in range(1, 11):
            todos_list = [*todos_list, *list(todos_filter[start:end])]
            start = end
            end += chunking_limit
            if i != 10:
                yield f'data: {json.dumps({'number': i})}\n\n'
            if i == 10:
                cache.set(f'todos-{chat_id}', todos_list)
                yield f'data: {json.dumps({'number': i})}\n\n'
            time.sleep(0.1)

    response = StreamingHttpResponse(chunking_data(), content_type='text/event-stream')
    response['Cache-Control'] = 'no-cache'
    return response


def remove_todo(request, id):
    try:
        Todo.objects.get(id=id).delete()
    except Todo.DoesNotExist:
        return JsonResponse({'status': 'error', 'msg': 'todo cannot delete'}, status=404)
    return JsonResponse({'status': 'ok'})


def complete_todo(request, id):
    try:
        Todo.objects.filter(id=id).update(is_completed=True)
    except Todo.DoesNotExist:
        return JsonResponse({'status': 'error', 'msg': 'todo cannot complete'}, status=404)
    return JsonResponse({'status': 'ok'})


def add_todo(request, chat_id):
    todo_title = request.POST.get('todo-title')
    print(type(chat_id))
    try:
        user = User.objects.get(chat_id=chat_id)
        todo = Todo.objects.create(user=user, title=todo_title)
    except Exception as e:
        return JsonResponse({'status': 'error', 'msg': 'todo cannot add'}, status=404)
    return JsonResponse({'status': 'ok', 'id': todo.id})

webapp/core/templates/html/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
          integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="https://telegram.org/js/telegram-web-app.js" defer></script>

    <title>Todo</title>
</head>
<body>
<div class="container">
    {% include 'html/loader.html' %}
    <form class="new-todo-container" method="POST">
        <input name="todo-title">
        <button type="submit">+</button>
    </form>
    <div class="todos-container">
    </div>
</div>
{% include 'js/index.js.html' %}
</body>
</html>

webapp/core/templates/html/loader.html
<div class="loader-container">
    <div class="progress-container">
        <div class="progress"></div>
    </div>
</div>

webapp/core/templates/html/todos_list.html
{% for td in todos %}
    <div class="todo {% if td.is_completed %}completed{% endif %}" data-id="{{ td.id }}">
        <div class="title {% if td.is_completed %}completed{% endif %}">{{ td.title }}</div>
        <div class="btn-container">
            {% if not td.is_completed %}
                <span class="complete-btn" onclick="complete_todo(this,{{ td.id }})">
                        <i class="fa-solid fa-check"></i>
                    </span>
            {% endif %}
            <span class="remove-btn" onclick="delete_todo(this,{{ td.id }})">
                        <i class="fa-solid fa-trash"></i>
                    </span>
        </div>
    </div>
{% endfor %}

webapp/core/templates/js/index.js.html
<script type="text/javascript">
    let progress = document.querySelector('.loader-container .progress')
    let todos_container = document.querySelector('.todos-container')
    let newTodoForm = document.querySelector('.new-todo-container')
    let todosList = []
    let chat_id
    let iniData


    async function load_todo(url) {
        await fetch(url, {headers: {'X-Requested-With': 'XMLHttpRequest'}}).then(res => res.text()).then(res => {
            todos_container.innerHTML = res
        })
    }

    async function delete_todo(el, id) {
        url = '{% url 'todo:delete' 0 %}'.replace('0', id)
        await fetch(url, {headers: {'X-Requested-With': 'XMLHttpRequest'}}).then(res => res.json()).then(res => {
            if (res['status'] === 'ok') {
                console.log('fdsjfjkdshfdkjs')
                el.parentElement.parentElement.remove()
            }
        })
    }

    async function complete_todo(el, id) {
        url = '{% url 'todo:complete' 0 %}'.replace('0', id)
        await fetch(url, {headers: {'X-Requested-With': 'XMLHttpRequest'}}).then(res => res.json()).then(res => {
            if (res['status'] === 'ok') {
                let todo = el.parentElement.parentElement
                todo.classList.add('completed')
                todo.querySelector('.title').classList.add('completed')
                todo.querySelector('.complete-btn').remove()
            }
        })
    }

    async function add_todo(e) {
        e.preventDefault()
        let data = new FormData(newTodoForm)
        let url = '{% url 'todo:add' '0' %}'.replace('0', chat_id)
        if (data.get('todo-title').trim().length === 0) {
            return;
        }
        await fetch(url, {
            method: 'POST',
            headers: {'X-Requested-With': 'XMLHttpRequest'},
            body: data
        }).then(res => res.json()).then(res => {
            let todo_template = `   <div class="todo" data-id="${res['id']}">
        <div class="title">${data.get('todo-title')}</div>
        <div class="btn-container">
                <span class="complete-btn" onclick="complete_todo(this,${res['id']})">
                        <i class="fa-solid fa-check"></i>
                    </span>
            <span class="remove-btn" onclick="delete_todo(this,${res['id']})">
                        <i class="fa-solid fa-trash"></i>
                    </span>
        </div>
    </div>`
            todos_container.insertAdjacentHTML('afterbegin',todo_template)
        })
    }
    async function load_webapp(){
        let tg = window.Telegram.WebApp
        tg.ready()
        initData = tg.initDataUnsafe
        chat_id = initData.user.id
        tg.sendData(JSON.stringify({test:'arash'}))
    }
    window.addEventListener('load', () => {
        load_webapp()
        let url = '{% url 'todo:index' '0' %}'.replace('0',chat_id)
        const loader = new EventSource(url)
        loader.onmessage = (e) => {
            let data = JSON.parse(e.data)
            todosList.push(data['todo'])
            progress.style.width = data['number'] * 10 + '%'
            if (data['number'] === 10) {
                loader.close()
                document.querySelector('.loader-container').classList.add('hide')
                setTimeout(() => {
                }, 1000)
                load_todo(url)
            }
        }
        {% comment %}

loader.onopen = ()=>{
    console.log('connection is opened')
}

setTimeout(()=>{
    document.querySelector('.loader-container').style.display = 'none'
},2000).{% endcomment %}
    })
    newTodoForm.addEventListener('submit', add_todo)
</script>